# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424bc3b16b5213a7801bb122e62bafe85ce748633727b4200bd5e129a99abf7dcd8820f489c11523a4d38fa964190414e8ee0a397349198aa841dad760dea4be

test:
  secret_key_base: c90641a12f70e6db77bda8119cf33d07cb36d963b179ea6b818a1e4a0f15567896f69c66d4398f121af5d9290eb3d9e85155c1a70633ba4c8af14d2fa19f4319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
